version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaptive_bot
    env_file:
      - .env
    depends_on:
      - redis
    command: ["bash", "-c", "python -m adaptive_crypto_bot.run"]
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  redis-data: